//list of items 

let Items =  [
    { "item": "Airplane", "canFly": true },
    { "item": "Helicopter", "canFly": true },
    { "item": "Hot air balloon", "canFly": true },
    { "item": "Parachute", "canFly": true },
    { "item": "Glider", "canFly": true },
    { "item": "Drone", "canFly": true },
    { "item": "Kite", "canFly": true },
    { "item": "Rocket", "canFly": true },
    { "item": "Blimp", "canFly": true },
    { "item": "Balloon", "canFly": true },
    { "item": "Hang glider", "canFly": true },
    { "item": "Sailplane", "canFly": true },
    { "item": "Boat", "canFly": false },
    { "item": "Car", "canFly": false },
    { "item": "Bicycle", "canFly": false },
    { "item": "Bus", "canFly": false },
    { "item": "Train", "canFly": false },
    { "item": "Truck", "canFly": false },
    { "item": "Motorcycle", "canFly": false },
    { "item": "Horse", "canFly": false },
    { "item": "Elephant", "canFly": false },
    { "item": "Giraffe", "canFly": false },
    { "item": "Lion", "canFly": false },
    { "item": "Tiger", "canFly": false },
    { "item": "Bear", "canFly": false },
    { "item": "Wolf", "canFly": false },
    { "item": "Fox", "canFly": false },
    { "item": "Raccoon", "canFly": false },
    { "item": "Squirrel", "canFly": false },
    { "item": "Deer", "canFly": false },
    { "item": "Moose", "canFly": false },
    { "item": "Goose", "canFly": false },
    { "item": "Duck", "canFly": false },
    { "item": "Penguin", "canFly": false },
    { "item": "Owl", "canFly": true },
    { "item": "Eagle", "canFly": true },
    { "item": "Hawk", "canFly": true },
    { "item": "Falcon", "canFly": true },
    { "item": "Crow", "canFly": true },
    { "item": "Sparrow", "canFly": true },
    { "item": "Robin", "canFly": true },
    { "item": "Peacock", "canFly": true },
    { "item": "Seagull", "canFly": true },
    { "item": "Pelican", "canFly": true },
    { "item": "Swan", "canFly": true },
    { "item": "Butterfly", "canFly": true},
{ "item": "Antelope", "canFly": false },
{ "item": "Gazelle", "canFly": false },
{ "item": "Cheetah", "canFly": false },
{ "item": "Lizard", "canFly": false },
{ "item": "Snake", "canFly": false },
{ "item": "Frog", "canFly": false },
{ "item": "Fish", "canFly": false },
{ "item": "Shark", "canFly": false },
{ "item": "Whale", "canFly": false },
{ "item": "Dolphin", "canFly": false },
{ "item": "Tree", "canFly": false },
{ "item": "Rock", "canFly": false },
{ "item": "Mountain", "canFly": false },
{ "item": "River", "canFly": false },
{ "item": "Lake", "canFly": false },
{ "item": "Ocean", "canFly": false },
{ "item": "Book", "canFly": false },
{ "item": "Pencil", "canFly": false },
{ "item": "Paper", "canFly": false },
{ "item": "Phone", "canFly": false },
{ "item": "Computer", "canFly": false },
{ "item": "Television", "canFly": false },
{ "item": "Table", "canFly": false },
{ "item": "Chair", "canFly": false },
{ "item": "Couch", "canFly": false },
{ "item": "Blanket", "canFly": false },
{ "item": "Pillow", "canFly": false },
{ "item": "Clothing", "canFly": false },
{ "item": "Shoe", "canFly": false },
{ "item": "Hat", "canFly": false },
{ "item": "Glasses", "canFly": false },
{ "item": "Watch", "canFly": false },
{ "item": "Wallet", "canFly": false },
{ "item": "Purse", "canFly": false },
{ "item": "Key", "canFly": false },
{ "item": "Coin", "canFly": false },
{ "item": "Bottle", "canFly": false },
{ "item": "Can", "canFly": false },
{ "item": "Food", "canFly": false },
{ "item": "Bread", "canFly": false },
{ "item": "Fruit", "canFly": false },
{ "item": "Vegetable", "canFly": false },
{ "item": "Meat", "canFly": false },
{ "item": "Cheese", "canFly": false },
{ "item": "Egg", "canFly": false },
{ "item": "Airplane", "canFly": true },
{ "item": "Helicopter", "canFly": true },
{ "item": "Balloon", "canFly": true },
{ "item": "Blimp", "canFly": true },
{ "item": "Glider", "canFly": true },
{ "item": "Drone", "canFly": true },
{ "item": "Parachute", "canFly": true },
{ "item": "Kite", "canFly": true },
{ "item": "Ultralight aircraft", "canFly": true },
{ "item": "Hang glider", "canFly": true },
{ "item": "Jet pack", "canFly": true },
{ "item": "Space shuttle", "canFly": true },
{ "item": "Rocket", "canFly": true },
{ "item": "Hot air balloon", "canFly": true },
{ "item": "Wing suit", "canFly": true },
{ "item": "Paraglider", "canFly": true },
{ "item": "Gyrocopter", "canFly": true },
{ "item": "Biplane", "canFly": true },
{ "item": "Triplane", "canFly": true },
{ "item": "Seaplane", "canFly": true },
{ "item": "Propeller plane", "canFly": true },
{ "item": "Military aircraft", "canFly": true },
{ "item": "Firefighting aircraft", "canFly": true },
{ "item": "Cargo plane", "canFly": true },
{ "item": "Commercial airliner", "canFly": true },
{ "item": "Military helicopter", "canFly": true },
{ "item": "Rescue helicopter", "canFly": true },
{ "item": "Police helicopter", "canFly": true },
{ "item": "Air ambulance", "canFly": true },
{ "item": "Transport helicopter", "canFly": true },
{ "item": "News helicopter", "canFly": true },
{ "item": "Firefighting helicopter", "canFly": true },
{ "item": "Toy airplane", "canFly": true },
{ "item": "Model aircraft", "canFly": true },
{ "item": "Radio-controlled aircraft", "canFly": true },
{ "item": "Radio-controlled helicopter", "canFly": true },
{ "item": "Radio-controlled drone", "canFly": true },
{ "item": "Winged suits for skydiving", "canFly": true },
{ "item": "Winged suits for base jumping", "canFly": true },
{ "item": "Firefighting drone", "canFly": true },
{ "item": "Aerial survey drone", "canFly": true },
{ "item": "Delivery drone", "canFly": true },
{ "item": "Racing drone", "canFly": true },
{ "item": "Agricultural drone", "canFly": true },

];

export default Items;